// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "bbb2831167793dfe14dde477730eea9794e98e471fa111449ca4e237ea11e4a7")
