// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "814e05621755a6711a1571a8270a24d3455bc7d8f21d0d9d7086bd5a70d0237d")
