// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "6dc13d3e01826befbc7eec873370d4fed33f38820406c6e6a922f71bdccfc004")
